# Generated by Django 2.1 on 2018-08-23 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import handbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('device_id', models.CharField(blank=True, max_length=150, unique=True, verbose_name='device id')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('birthday', models.DateField(null=True, verbose_name='birthday')),
                ('job', models.TextField(blank=True)),
                ('enable_location_sharing', models.NullBooleanField(default=False, verbose_name='位置情報の共有')),
                ('triage_level', models.IntegerField(choices=[(0, 'red'), (1, 'yellow'), (2, 'green')], null=True, verbose_name='triage level')),
                ('is_pregnant', models.BooleanField(default=True, help_text="if user is a pregnant, pregnancy  et. al. is createdelse pregnancy record is not created and connected to other user's record")),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', handbook.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_weight', models.FloatField(null=True)),
                ('presentation', models.IntegerField(choices=[(0, 'unknown'), (1, 'cephalic presentation'), (2, 'breech presentation'), (3, 'shoulder presentation')], null=True, verbose_name='胎位')),
                ('placenta_attachment_site', models.IntegerField(choices=[(0, 'unknown'), (1, 'normal site'), (3, 'margin site'), (4, 'back site')], null=True, verbose_name='胎盤付着部位')),
                ('is_cervical_asthenia', models.NullBooleanField(verbose_name='頸管無力症')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField(verbose_name='検診日')),
                ('uterotome_length', models.FloatField(null=True, verbose_name='子宮底長')),
                ('weight', models.FloatField(null=True)),
                ('systolic_blood_pressure', models.FloatField(null=True, verbose_name='収縮期血圧/最高血圧')),
                ('diastolic_blood_pressure', models.FloatField(null=True, verbose_name='拡張期血圧/最低血圧')),
                ('abdominal_circumference', models.FloatField(null=True, verbose_name='腹囲')),
                ('edema', models.IntegerField(choices=[(0, '-'), (1, '+'), (2, '++')], null=True, verbose_name='浮腫')),
                ('urinary_protein', models.IntegerField(choices=[(0, '-'), (1, '+'), (2, '++')], null=True, verbose_name='尿蛋白')),
                ('urinary_sugar', models.IntegerField(choices=[(0, '-'), (1, '+'), (2, '++')], null=True, verbose_name='尿糖')),
                ('risk_of_threatened_abortion', models.BooleanField(default=False, verbose_name='切迫流の危険性')),
            ],
        ),
        migrations.CreateModel(
            name='GPAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravidity', models.IntegerField(null=True, verbose_name='妊娠回数')),
                ('parity', models.IntegerField(null=True, verbose_name='出産回数')),
                ('abortion', models.IntegerField(null=True, verbose_name='中絶回数')),
                ('caesarean_section', models.IntegerField(null=True, verbose_name='帝王切開の回数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.User')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('height', models.IntegerField(null=True)),
                ('weight_before_pregnancy', models.FloatField(null=True)),
                ('allergy', models.TextField(null=True)),
                ('medicine_in_medication', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.User')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(null=True, verbose_name='位置情報の精度')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('timestamp', models.DateTimeField(verbose_name='タイムスタンプ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_menstruation_start_date', models.DateField(null=True, verbose_name='最終月経開始日')),
                ('expected_delivery_date', models.DateField(null=True, verbose_name='出産予定日')),
                ('will_caesarean_section', models.NullBooleanField(verbose_name='帝王切開の予定')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='handbook.User')),
            ],
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='pregnancy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='handbook.Pregnancy'),
        ),
        migrations.AddField(
            model_name='child',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.Pregnancy'),
        ),
    ]
