# Generated by Django 2.1 on 2018-08-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='is_cervical_asthenia',
        ),
        migrations.RemoveField(
            model_name='child',
            name='placenta_attachment_site',
        ),
        migrations.RemoveField(
            model_name='consultationrecord',
            name='risk_of_threatened_abortion',
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='cervical_length',
            field=models.IntegerField(choices=[(0, '不明'), (1, '正常'), (2, '短い')], null=True, verbose_name='頸管長'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='placenta_attachment_site',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'normal site'), (2, 'margin site'), (3, 'back site')], null=True, verbose_name='胎盤付着部位'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='possibility_of_change_delivery_date',
            field=models.IntegerField(choices=[(0, '不明'), (1, 'あり'), (2, 'なし')], null=True, verbose_name='予定日修正'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='reason_for_caesarean_section',
            field=models.IntegerField(choices=[(0, 'その他'), (1, '骨盤位'), (2, '既往帝王切開'), (3, '胎盤位位置異常'), (4, '希望')], null=True, verbose_name='帝王切開の理由'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='risk_of_threatened_abortion',
            field=models.IntegerField(choices=[(0, '不明'), (1, 'あり'), (2, 'なし')], null=True, verbose_name='切迫流早産の危険性'),
        ),
        migrations.AlterField(
            model_name='child',
            name='presentation',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, '頭位'), (2, '骨盤位'), (3, '横位')], null=True, verbose_name='胎位'),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='edema',
            field=models.IntegerField(choices=[(0, '-'), (1, '+'), (2, '++'), (3, '+++'), (4, '++++')], null=True, verbose_name='浮腫'),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='urinary_protein',
            field=models.IntegerField(choices=[(0, '-'), (1, '+'), (2, '++'), (3, '+++'), (4, '++++')], null=True, verbose_name='尿蛋白'),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='urinary_sugar',
            field=models.IntegerField(choices=[(0, '-'), (1, '+'), (2, '++'), (3, '+++'), (4, '++++')], null=True, verbose_name='尿糖'),
        ),
        migrations.AlterField(
            model_name='gpac',
            name='abortion',
            field=models.IntegerField(null=True, verbose_name='自然/人工流産の回数'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='expected_delivery_date',
            field=models.DateField(null=True, verbose_name='分娩予定日'),
        ),
    ]
