# Generated by Django 2.1 on 2018-08-29 06:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_auto_20180828_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='reason_for_caesarean_section',
            field=models.IntegerField(choices=[(0, 'その他'), (1, '骨盤位'), (2, '既往帝王切開'), (3, '胎盤位E異常'), (4, '希望')], null=True, verbose_name='帝王切開の理由'),
        ),
    ]
