# Generated by Django 2.1 on 2018-08-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_auto_20180829_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=1024)),
                ('prefecture', models.CharField(blank=True, max_length=1024)),
                ('city', models.CharField(blank=True, max_length=1024)),
                ('street', models.CharField(blank=True, max_length=1024)),
                ('building', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address2',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handbook.User'),
        ),
    ]
