# Generated by Django 2.1 on 2018-11-14 04:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0005_auto_20180829_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='title')),
                ('plcae', models.IntegerField(choices=[(0, '現在地'), (1, '自宅')], verbose_name='トリガーの場所')),
                ('role', models.IntegerField(choices=[(0, '特定のアカウント'), (1, '主治医'), (2, '災害医療コーディネーター'), (3, '小児周産期リエゾン'), (4, '医療班のメンバー')], verbose_name='アクセスを許すロール')),
                ('full_name', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='フルネーム')),
                ('birthday', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='誕生日')),
                ('job', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='職業')),
                ('tel', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='電話番号')),
                ('address', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='住所')),
                ('gravidity', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='妊娠回数')),
                ('parity', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='出産回数')),
                ('abortion', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='自然/人工流産の回数')),
                ('caesarean_section', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='帝王切開の回数')),
                ('last_menstruation_start_date', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='最終月経開始日')),
                ('expected_delivery_date', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='分娩予定日')),
                ('will_caesarean_section', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='帝王切開の予定')),
                ('reason_for_caesarean_section', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='帝王切開の理由')),
                ('possibility_of_change_delivery_date', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='予定日修正')),
                ('placenta_attachment_site', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='胎盤付着部位')),
                ('risk_of_threatened_abortion', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='切迫流早産の危険性')),
                ('uterotome_length', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='子宮底長')),
                ('weight', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='体重')),
                ('systolic_blood_pressure', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='最高血圧')),
                ('diastolic_blood_pressure', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='最低血圧')),
                ('abdominal_circumference', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='腹囲')),
                ('edema', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='浮腫')),
                ('urinary_protein', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='尿蛋白')),
                ('urinary_sugar', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='尿糖')),
                ('cervical_length', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='頚管長')),
                ('estimated_weibht', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='推定体重')),
                ('presentation', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='胎位')),
                ('location', models.IntegerField(choices=[(0, '許可'), (1, '許可しない')], verbose_name='職業')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='full name')),
                ('birthday', models.DateField(null=True, verbose_name='birthday')),
                ('job', models.TextField(blank=True)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='birth_already',
            field=models.NullBooleanField(verbose_name='出産済み'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='birthday',
            field=models.DateField(null=True, verbose_name='出産日'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handbook.User'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.User'),
        ),
    ]
