# Generated by Django 2.1 on 2018-11-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0007_auto_20181114_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='birth_already',
            field=models.BooleanField(default=False, verbose_name='出産済み'),
        ),
    ]
