# Generated by Django 2.1 on 2018-11-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0008_auto_20181114_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, '不明'), (1, '経膣分娩'), (2, '帝王切開')], null=True, verbose_name='分娩方法'),
        ),
    ]
