# Generated by Django 2.1 on 2018-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0009_pregnancy_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrol',
            name='abdominal_circumference',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='diastolic_blood_pressure',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='possibility_of_change_delivery_date',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='systolic_blood_pressure',
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='allergy_key',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='アレルギー情報'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='area_disaster_medical_coordinator',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='地域災害医療コーディネーター'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='blood_pressure',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='最高/最低血圧'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='disaster_medical_volunteer_team',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='災害医療ボランティアチーム'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='height',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='身長'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='insurance_medical_activity_team',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='保険医療活動チーム'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='local_government_stuff',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='地方自治体の職員など'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='location_24h',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='発災の24時間負けら現在までの位置情報'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='location_after_occurrence',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='発災後から現在までの位置情報'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='medical_history',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='既往歴'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='num_of_children',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='分娩予定日'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='obstetric_medical_support_liaison_member',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='小児周産期リエゾンメンバー'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='prefecture_disaster_medical_coordinator',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='都道府県災害医療コーディネーター'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='schedule_date_correction',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='予定日修正'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='taking_drugs',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='服用中の薬'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='weight_before_pregnancy',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='妊娠前体重'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='abortion',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='自然/人工流産の回数'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='address',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='birthday',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='caesarean_section',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='帝王切開の回数'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='cervical_length',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='頚管長'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='edema',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='浮腫'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='estimated_weibht',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='推定体重'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='expected_delivery_date',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='分娩予定日'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='full_name',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='フルネーム'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='gravidity',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='妊娠回数'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='job',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='現在の就労状況(就労の有無・仕事内容・通勤時間・就労時間など)'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='last_menstruation_start_date',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='最終月経開始日'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='location',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='過去記録されたすべての位置情報'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='parity',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='出産回数'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='placenta_attachment_site',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='胎盤付着部位'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='plcae',
            field=models.IntegerField(choices=[(0, '現在地'), (1, '自宅')], null=True, verbose_name='トリガーの場所'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='presentation',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='胎位'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='reason_for_caesarean_section',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='帝王切開の理由'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='risk_of_threatened_abortion',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='切迫流早産の危険性'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='role',
            field=models.IntegerField(choices=[(0, '特定のアカウント'), (1, '主治医'), (2, '災害医療コーディネーター'), (3, '小児周産期リエゾン'), (4, '医療班のメンバー')], null=True, verbose_name='アクセスを許すロール'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='tel',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='urinary_protein',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='尿蛋白'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='urinary_sugar',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='尿糖'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='uterotome_length',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='子宮底長'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='weight',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='will_caesarean_section',
            field=models.IntegerField(choices=[(0, 'いかなる場合も共有しない'), (1, '大規模災害時のみ'), (2, '中規模以上の災害時'), (3, '小規模以上の災害時')], null=True, verbose_name='帝王切開の予定'),
        ),
    ]
