# Generated by Django 2.1 on 2018-12-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0010_auto_20181218_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='experiment_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='実験番号'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='is_assisted',
            field=models.NullBooleanField(verbose_name='アシストの有無'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='subject_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='被験者番号'),
        ),
    ]
