# Generated by Django 2.1 on 2018-12-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0011_auto_20181218_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='estimated_weibht',
            new_name='estimated_weight',
        ),
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='location',
            new_name='location_all',
        ),
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='schedule_date_correction',
            new_name='scheduled_date_correction',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='plcae',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='role',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='title',
        ),
    ]
