# Generated by Django 2.1 on 2018-12-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0013_accesscontrol_suggest_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='change_num',
            field=models.IntegerField(null=True, verbose_name='手動で変更した回数'),
        ),
    ]
