# Generated by Django 2.1 on 2019-03-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0014_accesscontrol_change_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
    ]
